### ISSUE TITLE
Specs don't pass under REE ruby

### ISSUE THREAD

**Issue by anlek** [anlek/mongify#6]
```
Failures:

  1) Mongify::Database::Table before_save should work
     Failure/Error: row.admin = row.delete('permission').to_i > 50
     NoMethodError:
       undefined method `admin=' for [{"permission"=>"51"}, nil]:Array
     # ./spec/mongify/database/table_spec.rb:195
     # ./spec/../lib/mongify/database/table.rb:182:in `call'
     # ./spec/../lib/mongify/database/table.rb:182:in `run_before_save'
     # ./spec/../lib/mongify/database/table.rb:131:in `translate'
     # ./spec/mongify/database/table_spec.rb:215

  2) Mongify::Database::Table before_save run_before_save should create a new DataRow
     Failure/Error: row.admin = row.delete('permission').to_i > 50
     NoMethodError:
       undefined method `admin=' for [{"first_name"=>"Bob"}, nil]:Array
     # ./spec/mongify/database/table_spec.rb:195
     # ./spec/../lib/mongify/database/table.rb:182:in `call'
     # ./spec/../lib/mongify/database/table.rb:182:in `run_before_save'
     # ./spec/mongify/database/table_spec.rb:211:in `send'
     # ./spec/mongify/database/table_spec.rb:211
```
